
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'brandalley_dbt'
profile: 'brandalley_dbt'
version: '1.0.0'
config-version: 2

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Append dbt default query comment to make debugging in BQ easier
query-comment:
  append: True



# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  brandalley_dbt:
    +schema: analytics
    core:
      +schema: core
      +materialized: table
    magento:
      +schema: magento
      +materialized: table 
      +tags:
        - "lightdash"
    crm:
      +schema: emarsys
    customer_service:
      +schema: customer_service
      zendesk:
        +schema: zendesk_model
      zohodesk:
        +schema: zohodesk_model
    sources:
      streamkap_current:
        +on_schema_change: "append_new_columns"
        +schema: streamkap_current
        sales:
          +post-hook: "delete {{this}} where __deleted = true"
        customers:
          +post-hook: "delete {{this}} where __deleted = true"

vars:
  # Needed to keep the surrogate_key function treating null as empty strings following upgrade of db-utils
  surrogate_key_treat_nulls_as_empty_strings: true
  using_domain_names:         False         #Disable if you are not using domain names
  using_organization_tags:    False         #Disable if you are not using organization tags