select  
case 
when cpev.value like ('Home>%') then "Homeware"
when cpev.value like ('Home & Garden>%') then "Homeware"
when cpev.value like ('Gifts>%') then "Festival"
when cpev.value like ('Kids>%') then "Kidswear"
when cpev.value like ('Christmas>%') then "Festival"
when cpev.value like ('Lingerie>%') then "Lingerie & Swimwear"
when cpev.value like ('Outlet>%') then "Outlet"
when cpev.value like ('Men>Tops%') then "RTW"
when cpev.value like ('Men>Trousers>%') then "RTW"
when cpev.value like ('Men>Underwear>%') then "Lingerie & Swimwear"
when cpev.value like ('Men>Accessories>%') then "Accessories"
when cpev.value like ('Men>Clothing>%') then "RTW"
when cpev.value like ('Men>Fleeces%') then "RTW"
when cpev.value like ('Men>Jeans>%') then "RTW"
when cpev.value like ('Men>Knitwear>%') then "RTW"
when cpev.value like ('Men>Onesies>%') then "RTW"
when cpev.value like ('Men>Outerwear>%') then "RTW"
when cpev.value like ('Men>Shirts>%') then "RTW"
when cpev.value like ('Men>Footwear>%') then "Footwear"
when cpev.value like ('Men>Shoes>%') then "Footwear"
when cpev.value like ('Men>Shorts>%') then "RTW"
when cpev.value like ('Men>Sportswear%') then "RTW"
when cpev.value like ('Men>Suits>%') then "RTW"
when cpev.value like ('Men>Swimwear>%') then "Lingerie & Swimwear"
when cpev.value like ('Men>Nightwear>%') then "Lingerie & Swimwear"
when cpev.value like ('Sports%') then "Active"
when cpev.value like ('Women>Accessories%') then "Accessories"
when cpev.value like ('Women>Blouses%') then "RTW"
when cpev.value like ('Women>Clothing>%') then "RTW"
when cpev.value like ('Women>Dresses>%') then "RTW"
when cpev.value like ('Women>Fleeces%') then "RTW"
when cpev.value like ('Women>Footwear%') then "Footwear"
when cpev.value like ('Women>Handbags>%') then "Accessories"
when cpev.value like ('Women>Jeans>%') then "RTW"
when cpev.value like ('Women>Knitwear>%') then "RTW"
when cpev.value like ('Women>Lingerie>%') then "Lingerie & Swimwear"
when cpev.value like ('Women>Onesies>%') then "RTW"
when cpev.value like ('Women>Outerwear>%') then "RTW"
when cpev.value like ('Women>Playsuits%') then "RTW"
when cpev.value like ('Women>Shoes%') then "Footwear"
when cpev.value like ('Women>Shorts>%') then "RTW"
when cpev.value like ('Women>Skirts>%') then "RTW"
when cpev.value like ('Women>Sportswear%') then "Active"
when cpev.value like ('Women>Tops%') then "RTW"
when cpev.value like ('Women>Trousers%') then "RTW"
when cpev.value like ('Women>Maternity%') then "RTW"
when cpev.value like ('Women>Jeans%') then "RTW"
when cpev.value like ('Women>Outerwear%') then "RTW"
when cpev.value like ('Beauty>%') then "Beauty"
else "Others" end as Category,
sfo.status,
sfo.customer_id,
sfo.increment_id
from {{ ref('stg__sales_flat_order') }} sfo
left join {{ ref('stg__customer_entity') }} ce on ce.entity_id = sfo.customer_id
left join {{ ref('stg__sales_flat_order_item') }} sfoi on sfo.entity_id = sfoi.order_id and sfoi.parent_item_id is null
left join {{ ref('stg__catalog_product_entity_varchar') }} cpev ON cpev.entity_id = sfoi.product_id and cpev.attribute_id = 205