name: 'Production - Emarsys Live '
source: google-big-query-5x13w
type: raw_sql
rawSql: |
  SELECT
    *
  FROM
    `emarsys.emarsys_new_customers`
  WHERE
    DATE(_streamkap_loaded_at_ts) >= CURRENT_DATE()
primaryKey: hightouch_customerId
