{# /* 
    This macro is used to calculate a region from a postcode column
*/ #}

{% macro calculate_region_from_postcode(postcode) -%}
case
       when upper({{postcode}}) like 'AB%' then 'Scotland'
       when upper({{postcode}}) like 'AL%' then 'East England'
       when upper({{postcode}}) like 'BA%' then 'South West'
       when upper({{postcode}}) like 'BB%' then 'North West'
       when upper({{postcode}}) like 'BD%' then 'North West'
       when upper({{postcode}}) like 'BH%' then 'South West'
       when upper({{postcode}}) like 'BL%' then 'North West'
       when upper({{postcode}}) like 'BN%' then 'South East'
       when upper({{postcode}}) like 'BR%' then 'Greater London'
       when upper({{postcode}}) like 'BS%' then 'South West'
       when upper({{postcode}}) like 'BT%' then 'Northern Ireland'
       when upper({{postcode}}) like 'CA%' then 'North West'
       when upper({{postcode}}) like 'CB%' then 'East England'
       when upper({{postcode}}) like 'CF%' then 'Wales'
       when upper({{postcode}}) like 'CH%' then 'North West'
       when upper({{postcode}}) like 'CM%' then 'East England'
       when upper({{postcode}}) like 'CO%' then 'East England'
       when upper({{postcode}}) like 'CR%' then 'Greater London'
       when upper({{postcode}}) like 'CT%' then 'South East'
       when upper({{postcode}}) like 'CV%' then 'West Midlands'
       when upper({{postcode}}) like 'CW%' then 'North West'
       when upper({{postcode}}) like 'DA%' then 'Greater London'
       when upper({{postcode}}) like 'DD%' then 'Scotland'
       when upper({{postcode}}) like 'DE%' then 'East Midlands'
       when upper({{postcode}}) like 'DG%' then 'Scotland'
       when upper({{postcode}}) like 'DH%' then 'North East'
       when upper({{postcode}}) like 'DL%' then 'North East'
       when upper({{postcode}}) like 'DN%' then 'Yorkshire & Humberside'
       when upper({{postcode}}) like 'DT%' then 'South West'
       when upper({{postcode}}) like 'DY%' then 'West Midlands'
       when upper({{postcode}}) like 'EC%' then 'Greater London'
       when upper({{postcode}}) like 'EH%' then 'Scotland'
       when upper({{postcode}}) like 'EN%' then 'Greater London'
       when upper({{postcode}}) like 'EX%' then 'South West'
       when upper({{postcode}}) like 'FK%' then 'Scotland'
       when upper({{postcode}}) like 'FY%' then 'North West'
       when upper({{postcode}}) like 'GL%' then 'South West'
       when upper({{postcode}}) like 'GU%' then 'South East'
       when upper({{postcode}}) like 'GY%' then 'Channel Islands'
       when upper({{postcode}}) like 'HA%' then 'Greater London'
       when upper({{postcode}}) like 'HD%' then 'North West'
       when upper({{postcode}}) like 'HG%' then 'Yorkshire & Humberside'
       when upper({{postcode}}) like 'HP%' then 'South East'
       when upper({{postcode}}) like 'HR%' then 'West Midlands'
       when upper({{postcode}}) like 'HS%' then 'Scotland'
       when upper({{postcode}}) like 'HU%' then 'Yorkshire & Humberside'
       when upper({{postcode}}) like 'HX%' then 'North West'
       when upper({{postcode}}) like 'IG%' then 'Greater London'
       when upper({{postcode}}) like 'IM%' then 'North West'
       when upper({{postcode}}) like 'IP%' then 'East England'
       when upper({{postcode}}) like 'IV%' then 'Scotland'
       when upper({{postcode}}) like 'JE%' then 'Channel Islands'
       when upper({{postcode}}) like 'KA%' then 'Scotland'
       when upper({{postcode}}) like 'KT%' then 'Greater London'
       when upper({{postcode}}) like 'KW%' then 'Scotland'
       when upper({{postcode}}) like 'KY%' then 'Scotland'
       when upper({{postcode}}) like 'LA%' then 'North West'
       when upper({{postcode}}) like 'LD%' then 'Wales'
       when upper({{postcode}}) like 'LE%' then 'East Midlands'
       when upper({{postcode}}) like 'LL%' then 'Wales'
       when upper({{postcode}}) like 'LN%' then 'East England'
       when upper({{postcode}}) like 'LS%' then 'Yorkshire & Humberside'
       when upper({{postcode}}) like 'LU%' then 'East England'
       when upper({{postcode}}) like 'ME%' then 'South East'
       when upper({{postcode}}) like 'MK%' then 'South East'
       when upper({{postcode}}) like 'ML%' then 'Scotland'
       when upper({{postcode}}) like 'NE%' then 'North East'
       when upper({{postcode}}) like 'NG%' then 'East Midlands'
       when upper({{postcode}}) like 'NN%' then 'East Midlands'
       when upper({{postcode}}) like 'NP%' then 'Wales'
       when upper({{postcode}}) like 'NR%' then 'East England'
       when upper({{postcode}}) like 'NW%' then 'Greater London'
       when upper({{postcode}}) like 'OL%' then 'North West'
       when upper({{postcode}}) like 'OX%' then 'South East'
       when upper({{postcode}}) like 'PA%' then 'Scotland'
       when upper({{postcode}}) like 'PE%' then 'East England'
       when upper({{postcode}}) like 'PH%' then 'Scotland'
       when upper({{postcode}}) like 'PL%' then 'South West'
       when upper({{postcode}}) like 'PO%' then 'South East'
       when upper({{postcode}}) like 'PR%' then 'North West'
       when upper({{postcode}}) like 'RG%' then 'South East'
       when upper({{postcode}}) like 'RH%' then 'South East'
       when upper({{postcode}}) like 'RM%' then 'Greater London'
       when upper({{postcode}}) like 'SA%' then 'Wales'
       when upper({{postcode}}) like 'SE%' then 'Greater London'
       when upper({{postcode}}) like 'SG%' then 'South East'
       when upper({{postcode}}) like 'SK%' then 'North West'
       when upper({{postcode}}) like 'SL%' then 'South East'
       when upper({{postcode}}) like 'SM%' then 'Greater London'
       when upper({{postcode}}) like 'SN%' then 'South West'
       when upper({{postcode}}) like 'SO%' then 'South East'
       when upper({{postcode}}) like 'SP%' then 'South West'
       when upper({{postcode}}) like 'SR%' then 'North East'
       when upper({{postcode}}) like 'SS%' then 'East England'
       when upper({{postcode}}) like 'ST%' then 'West Midlands'
       when upper({{postcode}}) like 'SW%' then 'Greater London'
       when upper({{postcode}}) like 'SY%' then 'Wales'
       when upper({{postcode}}) like 'TA%' then 'South West'
       when upper({{postcode}}) like 'TD%' then 'Scotland'
       when upper({{postcode}}) like 'TF%' then 'West Midlands'
       when upper({{postcode}}) like 'TN%' then 'South East'
       when upper({{postcode}}) like 'TQ%' then 'South West'
       when upper({{postcode}}) like 'TR%' then 'South West'
       when upper({{postcode}}) like 'TS%' then 'North East'
       when upper({{postcode}}) like 'TW%' then 'Greater London'
       when upper({{postcode}}) like 'UB%' then 'Greater London'
       when upper({{postcode}}) like 'WA%' then 'North West'
       when upper({{postcode}}) like 'WC%' then 'Greater London'
       when upper({{postcode}}) like 'WD%' then 'Greater London'
       when upper({{postcode}}) like 'WF%' then 'Yorkshire & Humberside'
       when upper({{postcode}}) like 'WN%' then 'North West'
       when upper({{postcode}}) like 'WR%' then 'West Midlands'
       when upper({{postcode}}) like 'WS%' then 'West Midlands'
       when upper({{postcode}}) like 'WV%' then 'West Midlands'
       when upper({{postcode}}) like 'YO%' then 'Yorkshire & Humberside'
       when upper({{postcode}}) like 'ZE%' then 'Scotland'
       when upper({{postcode}}) like 'Z%' then 'Others'
       when upper({{postcode}}) like 'B%' then 'West Midlands'
       when upper({{postcode}}) like 'W%' then 'Greater London'
       when upper({{postcode}}) like 'S%' then 'Yorkshire & Humberside'
       when upper({{postcode}}) like 'N%' then 'Greater London'
       when upper({{postcode}}) like 'L%' then 'North West'
       when upper({{postcode}}) like 'G%' then 'Scotland'
       when upper({{postcode}}) like 'E%' then 'Greater London'
       when upper({{postcode}}) like 'M%' then 'North West'
       else 'Ireland'
       end

{% endmacro %}