{% macro calculate_region_from_postcode(postcode) -%}
case
       when {{postcode}} like 'AB%' then 'Scotland'
       when {{postcode}} like 'AL%' then 'East England'
       when {{postcode}} like 'BA%' then 'South West'
       when {{postcode}} like 'BB%' then 'North West'
       when {{postcode}} like 'BD%' then 'North West'
       when {{postcode}} like 'BH%' then 'South West'
       when {{postcode}} like 'BL%' then 'North West'
       when {{postcode}} like 'BN%' then 'South East'
       when {{postcode}} like 'BR%' then 'Greater London'
       when {{postcode}} like 'BS%' then 'South West'
       when {{postcode}} like 'BT%' then 'Northern Ireland'
       when {{postcode}} like 'CA%' then 'North West'
       when {{postcode}} like 'CB%' then 'East England'
       when {{postcode}} like 'CF%' then 'Wales'
       when {{postcode}} like 'CH%' then 'North West'
       when {{postcode}} like 'CM%' then 'East England'
       when {{postcode}} like 'CO%' then 'East England'
       when {{postcode}} like 'CR%' then 'Greater London'
       when {{postcode}} like 'CT%' then 'South East'
       when {{postcode}} like 'CV%' then 'West Midlands'
       when {{postcode}} like 'CW%' then 'North West'
       when {{postcode}} like 'DA%' then 'Greater London'
       when {{postcode}} like 'DD%' then 'Scotland'
       when {{postcode}} like 'DE%' then 'East Midlands'
       when {{postcode}} like 'DG%' then 'Scotland'
       when {{postcode}} like 'DH%' then 'North East'
       when {{postcode}} like 'DL%' then 'North East'
       when {{postcode}} like 'DN%' then 'Yorkshire & Humberside'
       when {{postcode}} like 'DT%' then 'South West'
       when {{postcode}} like 'DY%' then 'West Midlands'
       when {{postcode}} like 'EC%' then 'Greater London'
       when {{postcode}} like 'EH%' then 'Scotland'
       when {{postcode}} like 'EN%' then 'Greater London'
       when {{postcode}} like 'EX%' then 'South West'
       when {{postcode}} like 'FK%' then 'Scotland'
       when {{postcode}} like 'FY%' then 'North West'
       when {{postcode}} like 'GL%' then 'South West'
       when {{postcode}} like 'GU%' then 'South East'
       when {{postcode}} like 'GY%' then 'Channel Islands'
       when {{postcode}} like 'HA%' then 'Greater London'
       when {{postcode}} like 'HD%' then 'North West'
       when {{postcode}} like 'HG%' then 'Yorkshire & Humberside'
       when {{postcode}} like 'HP%' then 'South East'
       when {{postcode}} like 'HR%' then 'West Midlands'
       when {{postcode}} like 'HS%' then 'Scotland'
       when {{postcode}} like 'HU%' then 'Yorkshire & Humberside'
       when {{postcode}} like 'HX%' then 'North West'
       when {{postcode}} like 'IG%' then 'Greater London'
       when {{postcode}} like 'IM%' then 'North West'
       when {{postcode}} like 'IP%' then 'East England'
       when {{postcode}} like 'IV%' then 'Scotland'
       when {{postcode}} like 'JE%' then 'Channel Islands'
       when {{postcode}} like 'KA%' then 'Scotland'
       when {{postcode}} like 'KT%' then 'Greater London'
       when {{postcode}} like 'KW%' then 'Scotland'
       when {{postcode}} like 'KY%' then 'Scotland'
       when {{postcode}} like 'LA%' then 'North West'
       when {{postcode}} like 'LD%' then 'Wales'
       when {{postcode}} like 'LE%' then 'East Midlands'
       when {{postcode}} like 'LL%' then 'Wales'
       when {{postcode}} like 'LN%' then 'East England'
       when {{postcode}} like 'LS%' then 'Yorkshire & Humberside'
       when {{postcode}} like 'LU%' then 'East England'
       when {{postcode}} like 'ME%' then 'South East'
       when {{postcode}} like 'MK%' then 'South East'
       when {{postcode}} like 'ML%' then 'Scotland'
       when {{postcode}} like 'NE%' then 'North East'
       when {{postcode}} like 'NG%' then 'East Midlands'
       when {{postcode}} like 'NN%' then 'East Midlands'
       when {{postcode}} like 'NP%' then 'Wales'
       when {{postcode}} like 'NR%' then 'East England'
       when {{postcode}} like 'NW%' then 'Greater London'
       when {{postcode}} like 'OL%' then 'North West'
       when {{postcode}} like 'OX%' then 'South East'
       when {{postcode}} like 'PA%' then 'Scotland'
       when {{postcode}} like 'PE%' then 'East England'
       when {{postcode}} like 'PH%' then 'Scotland'
       when {{postcode}} like 'PL%' then 'South West'
       when {{postcode}} like 'PO%' then 'South East'
       when {{postcode}} like 'PR%' then 'North West'
       when {{postcode}} like 'RG%' then 'South East'
       when {{postcode}} like 'RH%' then 'South East'
       when {{postcode}} like 'RM%' then 'Greater London'
       when {{postcode}} like 'SA%' then 'Wales'
       when {{postcode}} like 'SE%' then 'Greater London'
       when {{postcode}} like 'SG%' then 'South East'
       when {{postcode}} like 'SK%' then 'North West'
       when {{postcode}} like 'SL%' then 'South East'
       when {{postcode}} like 'SM%' then 'Greater London'
       when {{postcode}} like 'SN%' then 'South West'
       when {{postcode}} like 'SO%' then 'South East'
       when {{postcode}} like 'SP%' then 'South West'
       when {{postcode}} like 'SR%' then 'North East'
       when {{postcode}} like 'SS%' then 'East England'
       when {{postcode}} like 'ST%' then 'West Midlands'
       when {{postcode}} like 'SW%' then 'Greater London'
       when {{postcode}} like 'SY%' then 'Wales'
       when {{postcode}} like 'TA%' then 'South West'
       when {{postcode}} like 'TD%' then 'Scotland'
       when {{postcode}} like 'TF%' then 'West Midlands'
       when {{postcode}} like 'TN%' then 'South East'
       when {{postcode}} like 'TQ%' then 'South West'
       when {{postcode}} like 'TR%' then 'South West'
       when {{postcode}} like 'TS%' then 'North East'
       when {{postcode}} like 'TW%' then 'Greater London'
       when {{postcode}} like 'UB%' then 'Greater London'
       when {{postcode}} like 'WA%' then 'North West'
       when {{postcode}} like 'WC%' then 'Greater London'
       when {{postcode}} like 'WD%' then 'Greater London'
       when {{postcode}} like 'WF%' then 'Yorkshire & Humberside'
       when {{postcode}} like 'WN%' then 'North West'
       when {{postcode}} like 'WR%' then 'West Midlands'
       when {{postcode}} like 'WS%' then 'West Midlands'
       when {{postcode}} like 'WV%' then 'West Midlands'
       when {{postcode}} like 'YO%' then 'Yorkshire & Humberside'
       when {{postcode}} like 'ZE%' then 'Scotland'
       when {{postcode}} like 'Z%' then 'Others'
       when {{postcode}} like 'B%' then 'West Midlands'
       when {{postcode}} like 'W%' then 'Greater London'
       when {{postcode}} like 'S%' then 'Yorkshire & Humberside'
       when {{postcode}} like 'N%' then 'Greater London'
       when {{postcode}} like 'L%' then 'North West'
       when {{postcode}} like 'G%' then 'Scotland'
       when {{postcode}} like 'E%' then 'Greater London'
       when {{postcode}} like 'M%' then 'North West'
       else 'Ireland'
       end

{% endmacro %}