{{config(
    materialized='incremental',
    unique_key='ba_site_entity_id',
	cluster_by='entity_id',
)}}

select
    'UK-' || {{ config.get('unique_key')|replace('ba_site_', '') }} as {{ config.get('unique_key') }},
    'UK'                                                            as ba_site,
    entity_id,
    parent_id,
    base_price,
    tax_amount,
    base_row_total,
    discount_amount,
    row_total,
    base_discount_amount,
    price_incl_tax,
    base_tax_amount,
    base_price_incl_tax,
    qty,
    base_cost,
    price,
    base_row_total_incl_tax,
    row_total_incl_tax,
    product_id,
    order_item_id,
    additional_data,
    description,
    sku,
    name,
    hidden_tax_amount,
    base_hidden_tax_amount,
    weee_tax_disposition,
    weee_tax_row_disposition,
    base_weee_tax_disposition,
    base_weee_tax_row_disposition,
    weee_tax_applied,
    base_weee_tax_applied_amount,
    base_weee_tax_applied_row_amnt,
    weee_tax_applied_amount,
    weee_tax_applied_row_amount,
    refund_reason_id,
    customer_refund_request,
    exported_to_sap,
    qty_returned_to_warehouse,
    _streamkap_source_ts_ms,
    _streamkap_ts_ms,
    _streamkap_offset,
    _streamkap_loaded_at_ts,
    __deleted,
    bq_last_processed_at
from {{ ref('stg_uk__sales_flat_creditmemo_item') }}
{% if is_incremental() %}
    where bq_last_processed_at > (select max(bq_last_processed_at) from {{this}} where ba_site = 'UK' )
{% endif %}

union all

select
    'FR-' || {{ config.get('unique_key')|replace('ba_site_', '') }} as {{ config.get('unique_key') }},
    'FR'                                                            as ba_site,
    entity_id,
    parent_id,
    base_price,
    tax_amount,
    base_row_total,
    discount_amount,
    row_total,
    base_discount_amount,
    price_incl_tax,
    base_tax_amount,
    base_price_incl_tax,
    qty,
    base_cost,
    price,
    base_row_total_incl_tax,
    row_total_incl_tax,
    product_id,
    order_item_id,
    additional_data,
    description,
    sku,
    name,
    hidden_tax_amount,
    base_hidden_tax_amount,
    weee_tax_disposition,
    weee_tax_row_disposition,
    base_weee_tax_disposition,
    base_weee_tax_row_disposition,
    weee_tax_applied,
    base_weee_tax_applied_amount,
    base_weee_tax_applied_row_amnt,
    weee_tax_applied_amount,
    weee_tax_applied_row_amount,
    refund_reason_id,
    customer_refund_request,
    exported_to_sap,
    qty_returned_to_warehouse,
    _streamkap_source_ts_ms,
    _streamkap_ts_ms,
    _streamkap_offset,
    _streamkap_loaded_at_ts,
    __deleted,
    bq_last_processed_at
from {{ ref('stg_fr__sales_flat_creditmemo_item') }}
{% if is_incremental() %}
    where bq_last_processed_at > (select max(bq_last_processed_at) from {{this}} where ba_site = 'FR' )
{% endif %}