{{config(
    materialized='incremental',
    unique_key='ba_site_entity_id',
	cluster_by='ba_site_entity_id',
)}}

select
    'UK-' || {{ config.get('unique_key')|replace('ba_site_', '') }} as {{ config.get('unique_key') }},
    'UK'                                                            as ba_site,
    entity_id,
    parent_id,
    timestamp(created_at) as created_at,
    timestamp(updated_at) as updated_at,
    path,
    position,
    level,
    children_count,
    store_id,
    allow_google,
    all_children,
    approved_by,
    available_sort_by,
    brand_attribution,
    category_brand_title,
    category_landingpagetype,
    category_menu_type,
    category_product_brand,
    category_product_gender,
    category_product_type,
    children,
    customer_segments,
    custom_apply_to_products,
    custom_design,
    custom_design_from,
    custom_design_to,
    custom_layout_update,
    custom_use_parent_settings,
    default_sort_by,
    delivery_info,
    description,
    display_brand_products,
    display_mode,
    emarsys_include_in_rss,
    emarsys_rss_order,
    extra_restrictions,
    filter_price_range,
    flashsale_promotional_banner,
    full_description,
    gender_attribution,
    group_tags,
    image,
    include_in_menu,
    is_active,
    is_anchor,
    landing_page,
    meta_description,
    meta_keywords,
    meta_title,
    name,
    outlet_landing_image,
    outlet_slider_content,
    outlet_slider_order,
    page_layout,
    path_in_store,
    preview_mode,
    private_sales_link,
    promotional_banner_link,
    promotional_date,
    promotion_date,
    promotion_options,
    promo_text,
    sale_end,
    sale_start,
    sale_type,
    show_out_of_stock,
    standard_image,
    tagline,
    thumbnail,
    umm_cat_label,
    umm_cat_target,
    umm_dd_blocks,
    umm_dd_columns,
    umm_dd_proportions,
    umm_dd_type,
    umm_dd_width,
    url_key,
    url_path,
    _streamkap_source_ts_ms,
    _streamkap_ts_ms,
    _streamkap_offset,
    _streamkap_loaded_at_ts,
    __deleted,
    bq_last_processed_at
from {{ ref('stg_uk__catalog_category_flat_store_1') }}
{% if is_incremental() %}
    where bq_last_processed_at > (select max(bq_last_processed_at) from {{this}} where ba_site = 'UK' )
{% endif %}

union all

select
    'FR-' || {{ config.get('unique_key')|replace('ba_site_', '') }} as {{ config.get('unique_key') }},
    'FR'                                                            as ba_site,
    entity_id,
    parent_id,
    created_at,
    updated_at,
    path,
    position,
    level,
    children_count,
    store_id,
    allow_google,
    all_children,
    approved_by,
    available_sort_by,
    brand_attribution,
    category_brand_title,
    category_landingpagetype,
    category_menu_type,
    category_product_brand,
    category_product_gender,
    category_product_type,
    children,
    customer_segments,
    custom_apply_to_products,
    custom_design,
    timestamp(null) as custom_design_from,
    timestamp(null) as custom_design_to,
    custom_layout_update,
    custom_use_parent_settings,
    default_sort_by,
    delivery_info,
    description,
    display_brand_products,
    display_mode,
    emarsys_include_in_rss,
    emarsys_rss_order,
    extra_restrictions,
    filter_price_range,
    flashsale_promotional_banner,
    full_description,
    gender_attribution,
    group_tags,
    image,
    include_in_menu,
    is_active,
    is_anchor,
    landing_page,
    meta_description,
    meta_keywords,
    meta_title,
    name,
    outlet_landing_image,
    outlet_slider_content,
    outlet_slider_order,
    page_layout,
    path_in_store,
    preview_mode,
    private_sales_link,
    promotional_banner_link,
    timestamp(null) as promotional_date,
    timestamp(null) as promotion_date,
    promotion_options,
    promo_text,
    timestamp(null) as sale_end,
    timestamp(null) as sale_start,
    sale_type,
    show_out_of_stock,
    standard_image,
    tagline,
    thumbnail,
    umm_cat_label,
    umm_cat_target,
    umm_dd_blocks,
    umm_dd_columns,
    umm_dd_proportions,
    umm_dd_type,
    umm_dd_width,
    url_key,
    url_path,
    _streamkap_source_ts_ms,
    _streamkap_ts_ms,
    _streamkap_offset,
    _streamkap_loaded_at_ts,
    __deleted,
    bq_last_processed_at
from {{ ref('stg_fr__catalog_category_flat_store_1') }}
{% if is_incremental() %}
    where bq_last_processed_at > (select max(bq_last_processed_at) from {{this}} where ba_site = 'FR' )
{% endif %}